chore: add prod config
navikt/regulus-maximus pull request #11
Opened 2024-09-24 07:05 UTC by helehar

2024-09-24 07:11 UTC, MikAoJk commented on .github/workflows/dev-deploy.yaml
No dev deploy?

2024-09-26 17:06 UTC, MikAoJk requested changes

2024-09-26 17:06 UTC, MikAoJk commented on nais/nais-prod.yaml
> +        pointInTimeRecovery: true
Ser ut som vi mangler, 
tier: db-custom-2-5120

2024-10-17 12:12 UTC, heinharaldsen commented on nais/nais-prod.yaml
> +        pointInTimeRecovery: true
Lagt til

2024-11-18 12:19 UTC, merged